---
image: docker:17.12.0-ce

stages:
  - lint
  - build
  - run

variables:
  PROJECT: example-docker-ci-on-gitlab

.anchors:
  - &REGISTRYLOGIN
    docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN}" "${CI_REGISTRY}"

yamllint:
  stage: lint
  variables:
    IMAGE: dcycle/yaml-lint
    SHA: sha256:22b33626d57e990399d38ecc648884fb44ab9638eb1d3e1a2ab835864427ec20
  script:
    - docker pull "${IMAGE}@${SHA}"
    - docker run -v "${CI_PROJECT_DIR}:/app"
                    "${IMAGE}@${SHA}"
                    $(find -name '*.yml' -o -name '*.yaml')

dockerfile:
  stage: build
  variables:
    IMAGE: "${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_SLUG}_${CI_PIPELINE_ID}"
    LATEST: "${CI_REGISTRY_IMAGE}:latest"
  script:
    - docker build -t "${IMAGE}" .
    - *REGISTRYLOGIN
    - docker push "${IMAGE}"
    - docker tag "${IMAGE}" "${LATEST}"
    - docker push "${LATEST}"
    - docker inspect "${IMAGE}"
        -f '{{index .RepoDigests 0}}'
        > "${PROJECT}.sha256"
  artifacts:
    paths:
      - '${PROJECT}.sha256'

docker:
  stage: run
  script:
    - *REGISTRYLOGIN
    - docker pull "$(cat ${PROJECT}.sha256)"
    - c=$(docker run
            --detach "$(cat ${PROJECT}.sha256)")
    - docker stop "${c}"
    - docker rm "${c}"
